sudo: 'required'
notifications:
  email: false

services:
  - 'docker'

cache:
  directories:
    - ${HOME}/.composer/cache

branches:
  only:
  - master

before_script:
  - make composer_install

script:
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
      make deploy;
    fi
